name: HW-4-5

on:
  push:
    branches: [main, master, hw4-5]
  pull_request:
    branches: [main, master, hw4-5]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: shop_user
          POSTGRES_PASSWORD: shop_password
          POSTGRES_DB: shop_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: hw2/hw
        run: |
          cd 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432 -U shop_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Run tests with coverage
        working-directory: hw2/hw
        env:
          DATABASE_URL: postgresql://shop_user:shop_password@localhost:5432/shop_db
        run: |
          python -m pytest --cov=shop_api --cov-report=xml --cov-report=term-missing --cov-fail-under=95

      - name: Display coverage
        working-directory: hw2/hw
        run: |
          echo "Coverage report:"
          cat coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
